-- FONTE DAS PEITA • configuração do Supabase
-- Rode este SQL no SQL Editor do seu projeto.

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  cat text not null,
  season text not null,
  price numeric(10,2) not null,
  image text default '',
  updated_at timestamptz not null default now()
);
create table if not exists public.banners (
  id bigint primary key,
  title text not null,
  subtitle text default '',
  image text default '',
  updated_at timestamptz not null default now()
);
create table if not exists public.settings (
  id bigint primary key,
  whatsapp text not null,
  instagram text default '',
  password text not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  external_reference text unique not null,
  status text not null default 'aguardando_pagamento',
  customer_name text not null,
  customer_email text not null,
  customer_phone text default '',
  cep text default '',
  street text default '',
  street_number text default '',
  neighborhood text default '',
  city text default '',
  uf text default '',
  complement text default '',
  shipping_company text default '',
  shipping_name text default '',
  shipping_price numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  mercado_pago_preference_id text default '',
  mercado_pago_payment_id text default '',
  payment_method text default '',
  payment_status_detail text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.banners enable row level security;
alter table public.settings enable row level security;
alter table public.orders enable row level security;

drop policy if exists products_public_select on public.products;
drop policy if exists products_public_insert on public.products;
drop policy if exists products_public_update on public.products;
drop policy if exists products_public_delete on public.products;
create policy products_public_select on public.products for select to anon using (true);
create policy products_public_insert on public.products for insert to anon with check (true);
create policy products_public_update on public.products for update to anon using (true) with check (true);
create policy products_public_delete on public.products for delete to anon using (true);

drop policy if exists banners_public_select on public.banners;
drop policy if exists banners_public_insert on public.banners;
drop policy if exists banners_public_update on public.banners;
drop policy if exists banners_public_delete on public.banners;
create policy banners_public_select on public.banners for select to anon using (true);
create policy banners_public_insert on public.banners for insert to anon with check (true);
create policy banners_public_update on public.banners for update to anon using (true) with check (true);
create policy banners_public_delete on public.banners for delete to anon using (true);

drop policy if exists settings_public_select on public.settings;
drop policy if exists settings_public_insert on public.settings;
drop policy if exists settings_public_update on public.settings;
create policy settings_public_select on public.settings for select to anon using (true);
create policy settings_public_insert on public.settings for insert to anon with check (true);
create policy settings_public_update on public.settings for update to anon using (true) with check (true);

insert into public.settings (id,whatsapp,instagram,password) values (1,'5512991580761','@fontedaspeita_ofc','050423') on conflict (id) do nothing;

-- Pedidos: não crie policies para anon. As Functions do Netlify usam a service_role.

-- STORAGE: crie um bucket público chamado exatamente: site-images
-- Depois rode as policies abaixo.
drop policy if exists site_images_public_select on storage.objects;
drop policy if exists site_images_public_insert on storage.objects;
drop policy if exists site_images_public_update on storage.objects;
drop policy if exists site_images_public_delete on storage.objects;
create policy site_images_public_select on storage.objects for select to anon using (bucket_id = 'site-images');
create policy site_images_public_insert on storage.objects for insert to anon with check (bucket_id = 'site-images');
create policy site_images_public_update on storage.objects for update to anon using (bucket_id = 'site-images') with check (bucket_id = 'site-images');
create policy site_images_public_delete on storage.objects for delete to anon using (bucket_id = 'site-images');
